/** MIT License
 *
 * Copyright (c) 2026 Humza Khan
 * <mohammed.khan.2024@uni.strath.ac.uk>
 * <https://github.com/humzak711>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
*/

#ifndef _IA32E_VMCS_H_
#define _IA32E_VMCS_H_

#include <generated/autoconf.h>
#include <stdWorkhorse.h>

typedef enum ia32eVtxVmcsAccess
{
    ia32eVtxVmcsAccessFull = 0,
    ia32eVtxVmcsAccessHigh = 1,
} ia32eVtxVmcsAccess_t;

typedef enum ia32eVtxVmcsType
{
    ia32eVtxVmcsTypeControl =       0,
    ia32eVtxVmcsTypeVmexit =        1,
    ia32eVtxVmcsTypeGuestState =    2,
    ia32eVtxVmcsTypeHostState =     3,
} ia32eVtxVmcsType_t;

typedef enum ia32eVtxVmcsWidth
{
    ia32eVtxVmcsWidthWord =      0,
    ia32eVtxVmcsWidthQword =     1,
    ia32eVtxVmcsWidthDword =     2,
    ia32eVtxVmcsWidthNatural =   3,
} ia32eVtxVmcsWidth_t;

#define IA32E_VTX_VMCS_ENC_COMPONENT(access, index, type, width) \
    (unsigned)((unsigned short)(access) |              \
               ((unsigned short)(index) << 1) |        \
               ((unsigned short)(type) << 10) |        \
               ((unsigned short)(width) << 13))
#define IA32E_VTX_VMCS_ENC_COMPONENT_FULL(index, type, width) \
    IA32E_VTX_VMCS_ENC_COMPONENT(ia32eVtxVmcsAccessFull, index, type, width)
#define IA32E_VTX_VMCS_ENC_COMPONENT_HIGH(index, type, width) \
    IA32E_VTX_VMCS_ENC_COMPONENT(ia32eVtxVmcsAccessHigh, index, type, width)
#define IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL(index, type, ia32eVtxVmcsWidthWord)
#define IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL(index, type, ia32eVtxVmcsWidthDword)
#define IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL(index, type, ia32eVtxVmcsWidthQword)
#define IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL(index, type, ia32eVtxVmcsWidthNatural)
#define IA32E_VTX_VMCS_ENC_COMPONENT_HIGH_16(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_HIGH(index, type, ia32eVtxVmcsWIdthWord)
#define IA32E_VTX_VMCS_ENC_COMPONENT_HIGH_32(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_HIGH(index, type, ia32eVtxVmcsWidthDword)
#define IA32E_VTX_VMCS_ENC_COMPONENT_HIGH_64(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_HIGH(index, type, ia32eVtxVmcsWidthQword)
#define IA32E_VTX_VMCS_ENC_COMPONENT_HIGH_NAT(index, type) \
    IA32E_VTX_VMCS_ENC_COMPONENT_HIGH(index, type, ia32eVtxVmcsWidthNatural)

// 16-bit fields (ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VPID \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(0, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_POSTED_INTERRUPT_NOTIFICATION_VECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(1, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EPTP_INDEX \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(2, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_HLAT_PREFIX_SIZE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(3, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_LAST_PID_POINTER_INDEX \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(4, ia32eVtxVmcsTypeControl)

// 16-bit fields (guest-state)
#define IA32E_VTX_VMCS_GUEST_ES_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(0, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_CS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(1, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_SS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(2, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_DS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(3, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_FS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(4, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_GS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(5, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_LDTR_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(6, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_TR_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(7, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_INTERRUPT_STATUS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(8, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_PML_INDEX \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(9, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_UINV \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(10, ia32eVtxVmcsTypeGuestState)

// 16-bit fields (host-state)
#define IA32E_VTX_VMCS_HOST_ES_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(0, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_CS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(1, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_SS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(2, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_DS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(3, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_FS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(4, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_GS_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(5, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_TR_SELECTOR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_16(6, ia32eVtxVmcsTypeHostState)

// 64-bit fields (control)
#define IA32E_VTX_VMCS_CTRL_IO_BITMAP_A \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(0, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_IO_BITMAP_B \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(1, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_MSR_BITMAPS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(2, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMEXIT_MSR_STORE_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(3, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMEXIT_MSR_LOAD_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(4, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMENTRY_MSR_LOAD_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(5, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EXECUTIVE_VMCS_POINTER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(6, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PML_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(7, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_TSC_OFFSET \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(8, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VIRTUAL_APIC_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(9, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_APIC_ACCESS_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(10, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_POSTED_INTERRUPT_DESCRIPTOR_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(11, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VM_FUNCTION_CONTROLS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(12, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EPTP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(13, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EOI_EXIT_BITMAP_0 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(14, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EOI_EXIT_BITMAP_1 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(15, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EOI_EXIT_BITMAP_2 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(16, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EOI_EXIT_BITMAP_3 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(17, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EPTP_LIST_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(18, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMREAD_BITMAP_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(19, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMWRITE_BITMAP_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(20, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VIRT_EXCEPTION_INFORMATION_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(21, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_XSS_EXITING_BITMAP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(22, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_ENCLS_EXITING_BITMAP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(23, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_SUB_PAGE_PERMISSION_TABLE_POINTER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(24, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_TSC_MULTIPLIER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(25, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PROCBASED_CTLS3 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(26, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_ENCLV_EXITING_BITMAP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(27, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_LOW_PASID_DIRECTORY_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(28, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_HIGH_PASID_DIRECTORY_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(29, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_SHARED_EPT_POINTER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(30, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PCONFIG_EXITING_BITMAP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(31, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_HLATP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(32, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PID_POINTER_TABLE_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(33, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_SECONDARY_VMEXIT_CONTROLS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(34, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_IA32E_SPEC_CTRL_MASK \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(35, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_IA32E_SPEC_CTRL_SHADOW \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(36, ia32eVtxVmcsTypeControl)

// 64-bit fields (read-only data)
#define IA32E_VTX_VMCS_RO_GUEST_PHYSICAL_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(0, ia32eVtxVmcsTypeVmexit)

// 64-bit fields (guest-state)
#define IA32E_VTX_VMCS_GUEST_VMCS_LINK_POINTER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(0, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_DEBUGCTL \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(1, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_PAT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(2, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_EFER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(3, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_PERF_GLOBAL_CTRL \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(4, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_PDPTE0 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(5, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_PDPTE1 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(6, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_PDPTE2 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(7, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_PDPTE3 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(8, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_BNDCFGS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(9, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_RTIT_CTL \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(10, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_LBR_CTL \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(11, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_PKRS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(12, ia32eVtxVmcsTypeGuestState)

// 64-bit fields (host-state)
#define IA32E_VTX_VMCS_HOST_IA32E_PAT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(0, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_EFER \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(1, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_PERF_GLOBAL_CTRL \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(2, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_PKRS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_64(3, ia32eVtxVmcsTypeHostState)

// 32-bit fields (ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PINBASED_CONTROLS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(0, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PROCBASED_CTLS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(1, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_EXCEPTION_BITMAP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(2, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PAGE_FAULT_ERROR_CODE_MASK \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(3, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PAGE_FAULT_ERROR_CODE_MATCH \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(4, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR3_TARGET_COUNT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(5, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PRIMARY_VMEXIT_CONTROLS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(6, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMEXIT_MSR_STORE_COUNT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(7, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMEXIT_MSR_LOAD_COUNT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(8, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMENTRY_CONTROLS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(9, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMENTRY_MSR_LOAD_COUNT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(10, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMENTRY_INTERRUPT_INFO \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(11, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMENTRY_INTERRUPT_ERROR_CODE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(12, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_VMENTRY_INSTRUCTION_LENGTH \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(13, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_TPR_THRESHOLD \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(14, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PROCBASED_CTLS2 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(15, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PLE_GAP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(16, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_PLE_WINDOW \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(17, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_INSTRUCTION_TIMEOUT_CONTROL \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(18, ia32eVtxVmcsTypeControl)

// 32-bit fields (read-only data)
#define IA32E_VTX_VMCS_RO_VM_INSTRUCTION_ERROR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(0, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_EXIT_REASON \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(1, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_VMEXIT_INTERRUPT_INFO \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(2, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_VMEXIT_INTERRUPT_ERROR_CODE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(3, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_IDT_VECTORING_INFO_FIELD \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(4, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_IDT_VECTORING_ERROR_CODE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(5, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_VMEXIT_INSTRUCTION_LENGTH \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(6, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_VMEXIT_INSTRUCTION_INFO \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(7, ia32eVtxVmcsTypeVmexit)

// 32-bit fields (guest-state)
#define IA32E_VTX_VMCS_GUEST_ES_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(0, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_CS_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(1, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_SS_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(2, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_DS_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(3, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_FS_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(4, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_GS_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(5, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_LDTR_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(6, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_TR_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(7, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_GDTR_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(8, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IDTR_LIMIT \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(9, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_ES_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(10, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_CS_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(11, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_SS_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(12, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_DS_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(13, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_FS_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(14, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_GS_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(15, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_LDTR_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(16, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_TR_ACCESS_RIGHTS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(17, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_INTERRUPTIBILITY_STATE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(18, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_ACTIVITY_STATE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(19, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_SMBASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(20, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_SYSENTER_CS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(21, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_VMX_PREEMPTION_TIMER_VALUE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(23, ia32eVtxVmcsTypeGuestState)

// 32-bit fields (host-state)
#define IA32E_VTX_VMCS_HOST_IA32E_SYSENTER_CS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_32(0, ia32eVtxVmcsTypeHostState)

// natural-width fields (ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR0_GUEST_HOST_MASK \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(0, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR4_GUEST_HOST_MASK \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(1, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR0_READ_SHADOW \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(2, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR4_READ_SHADOW \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(3, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR3_TARGET_VALUE_0 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(4, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR3_TARGET_VALUE_1 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(5, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR3_TARGET_VALUE_2 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(6, ia32eVtxVmcsTypeControl)
#define IA32E_VTX_VMCS_CTRL_CR3_TARGET_VALUE_3 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(7, ia32eVtxVmcsTypeControl)

// natural-width fields (read-only data)
#define IA32E_VTX_VMCS_RO_EXIT_QUALIFICATION \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(0, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_IO_RCX \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(1, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_IO_RSI \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(2, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_IO_RDI \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(3, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_IO_RIP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(4, ia32eVtxVmcsTypeVmexit)
#define IA32E_VTX_VMCS_RO_GUEST_LINEAR_ADDRESS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(5, ia32eVtxVmcsTypeVmexit)

// natural-width fields (guest-state)
#define IA32E_VTX_VMCS_GUEST_CR0 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(0, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_CR3 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(1, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_CR4 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(2, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_ES_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(3, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_CS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(4, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_SS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(5, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_DS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(6, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_FS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(7, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_GS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(8, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_LDTR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(9, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_TR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(10, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_GDTR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(11, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IDTR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(12, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_DR7 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(13, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_RSP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(14, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_RIP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(15, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_RFLAGS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(16, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_PENDING_DEBUG_EXCEPTIONS \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(17, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_SYSENTER_ESP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(18, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_SYSENTER_EIP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(19, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_S_CET \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(20, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_SSP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(21, ia32eVtxVmcsTypeGuestState)
#define IA32E_VTX_VMCS_GUEST_IA32E_INTERRUPT_SSP_TABLE_ADDR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(22, ia32eVtxVmcsTypeGuestState)

// natural-width fields (host-state)
#define IA32E_VTX_VMCS_HOST_CR0 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(0, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_CR3 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(1, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_CR4 \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(2, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_FS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(3, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_GS_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(4, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_TR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(5, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_GDTR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(6, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IDTR_BASE \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(7, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_SYSENTER_ESP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(8, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_SYSENTER_EIP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(9, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_RSP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(10, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_RIP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(11, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_S_CET \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(12, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_SSP \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(13, ia32eVtxVmcsTypeHostState)
#define IA32E_VTX_VMCS_HOST_IA32E_INTERRUPT_SSP_TABLE_ADDR \
    IA32E_VTX_VMCS_ENC_COMPONENT_FULL_NAT(14, ia32eVtxVmcsTypeHostState)

#define IA32E_VMCS_VPID_MAX     UINT16_MAX
#define IA32E_VMCS_VPID_COUNT   (IA32E_VMCS_VPID_MAX - 1)

#define IA32E_VTX_EXIT_REASON_EXCEPTION               0
#define IA32E_VTX_EXIT_REASON_EXT_INTR                1
#define IA32E_VTX_EXIT_REASON_TRIPLE_FAULT            2
#define IA32E_VTX_EXIT_REASON_INIT                    3
#define IA32E_VTX_EXIT_REASON_SIPI                    4
#define IA32E_VTX_EXIT_REASON_IO_SMI                  5
#define IA32E_VTX_EXIT_REASON_SMI                     6
#define IA32E_VTX_EXIT_REASON_INTR_WINDOW             7
#define IA32E_VTX_EXIT_REASON_NMI_WINDOW              8
#define IA32E_VTX_EXIT_REASON_TASK_SWITCH             9
#define IA32E_VTX_EXIT_REASON_CPUID                   10
#define IA32E_VTX_EXIT_REASON_GETSEC                  11
#define IA32E_VTX_EXIT_REASON_HLT                     12
#define IA32E_VTX_EXIT_REASON_INVD                    13
#define IA32E_VTX_EXIT_REASON_INVLPG                  14
#define IA32E_VTX_EXIT_REASON_RDPMC                   15
#define IA32E_VTX_EXIT_REASON_RDTSC                   16
#define IA32E_VTX_EXIT_REASON_RSM                     17
#define IA32E_VTX_EXIT_REASON_VMCALL                  18
#define IA32E_VTX_EXIT_REASON_VMCLEAR                 19
#define IA32E_VTX_EXIT_REASON_VMLAUNCH                20
#define IA32E_VTX_EXIT_REASON_VMPTRLD                 21
#define IA32E_VTX_EXIT_REASON_VMPTRST                 22
#define IA32E_VTX_EXIT_REASON_VMREAD                  23
#define IA32E_VTX_EXIT_REASON_VMRESUME                24
#define IA32E_VTX_EXIT_REASON_VMWRITE                 25
#define IA32E_VTX_EXIT_REASON_VMXOFF                  26
#define IA32E_VTX_EXIT_REASON_VMXON                   27
#define IA32E_VTX_EXIT_REASON_CR_ACCESS               28
#define IA32E_VTX_EXIT_REASON_DR_ACCESS               29
#define IA32E_VTX_EXIT_REASON_INOUT                   30
#define IA32E_VTX_EXIT_REASON_RDMSR                   31
#define IA32E_VTX_EXIT_REASON_WRMSR                   32
#define IA32E_VTX_EXIT_REASON_VMENTRY_INVAL_VMCS      33
#define IA32E_VTX_EXIT_REASON_VMENTRY_MSR_LOADING     34
#define IA32E_VTX_EXIT_REASON_MWAIT                   36
#define IA32E_VTX_EXIT_REASON_MTF                     37
#define IA32E_VTX_EXIT_REASON_MONITOR                 39
#define IA32E_VTX_EXIT_REASON_PAUSE                   40
#define IA32E_VTX_EXIT_REASON_MCE_DURING_ENTRY        41
#define IA32E_VTX_EXIT_REASON_TPR                     43
#define IA32E_VTX_EXIT_REASON_APIC_ACCESS             44
#define IA32E_VTX_EXIT_REASON_VIRTUALIZED_EOI         45
#define IA32E_VTX_EXIT_REASON_GDTR_IDTR               46
#define IA32E_VTX_EXIT_REASON_LDTR_TR                 47
#define IA32E_VTX_EXIT_REASON_EPT_FAULT               48
#define IA32E_VTX_EXIT_REASON_EPT_MISCONFIG           49
#define IA32E_VTX_EXIT_REASON_INVEPT                  50
#define IA32E_VTX_EXIT_REASON_RDTSCP                  51
#define IA32E_VTX_EXIT_REASON_VMX_PREEMPT             52
#define IA32E_VTX_EXIT_REASON_INVVPID                 53
#define IA32E_VTX_EXIT_REASON_WBINVD                  54
#define IA32E_VTX_EXIT_REASON_XSETBV                  55
#define IA32E_VTX_EXIT_REASON_APIC_WRITE              56
#define IA32E_VTX_EXIT_REASON_RDRAND                  57
#define IA32E_VTX_EXIT_REASON_INVPCID                 58
#define IA32E_VTX_EXIT_REASON_VMFUNC                  59
#define IA32E_VTX_EXIT_REASON_ENCLS                   60
#define IA32E_VTX_EXIT_REASON_RDSEED                  61
#define IA32E_VTX_EXIT_REASON_PGMOD_LOG_FULL          62
#define IA32E_VTX_EXIT_REASON_XSAVES                  63
#define IA32E_VTX_EXIT_REASON_XRSTORS                 64
#define IA32E_VTX_EXIT_REASON_PCONFIG                 65
#define IA32E_VTX_EXIT_REASON_SPP                     66
#define IA32E_VTX_EXIT_REASON_UMWAIT                  67
#define IA32E_VTX_EXIT_REASON_TPAUSE                  68
#define IA32E_VTX_EXIT_REASON_LOADIWKEY               69
#define IA32E_VTX_EXIT_REASON_ENCLV                   70
#define IA32E_VTX_EXIT_REASON_ENQCMD_PASID_FAILURE    72
#define IA32E_VTX_EXIT_REASON_ENQCMDS_FAILURE         73
#define IA32E_VTX_EXIT_REASON_BUSLOCK                 74
#define IA32E_VTX_EXIT_REASON_INSTRUCTION_TIMEOUT     75
#define IA32E_VTX_EXIT_REASON_SEAMCALL                76
#define IA32E_VTX_EXIT_REASON_TDCALL                  77
#define IA32E_VTX_EXIT_REASON_RDMSRLIST               78
#define IA32E_VTX_EXIT_REASON_WRMSRLIST               79

#define IA32E_VTX_VMCS_EXCEPTION_BITMAP_DEBUG_MASK              (1U << 1)
#define IA32E_VTX_VMCS_EXCEPTION_BITMAP_ALIGNMENT_CHECK_MASK    (1U << 17)

#define IA32E_VTX_VMCS_PINBASED_CTLS_EXTERNAL_INTERRUPT_EXITING_BIT  0
#define IA32E_VTX_VMCS_PINBASED_CTLS_NMI_EXITING_BIT                 3
#define IA32E_VTX_VMCS_PINBASED_CTLS_VIRTUAL_NMIS_BIT                5
#define IA32E_VTX_VMCS_PINBASED_CTLS_VMX_PREEMPTION_TIMER_BIT        6

#define IA32E_VTX_VMCS_PROCBASED_CTLS_INTERRUPT_WINDOW_EXITING_BIT   2
#define IA32E_VTX_VMCS_PROCBASED_CTLS_MWAIT_EXITING_BIT              10
#define IA32E_VTX_VMCS_PROCBASED_CTLS_RDPMC_EXITING_BIT              11
#define IA32E_VTX_VMCS_PROCBASED_CTLS_RDTSC_EXITING_BIT              12
#define IA32E_VTX_VMCS_PROCBASED_CTLS_NMI_WINDOW_EXITING_BIT         22
#define IA32E_VTX_VMCS_PROCBASED_CTLS_IO_BITMAPS_BIT                 25
#define IA32E_VTX_VMCS_PROCBASED_CTLS_MSR_BITMAPS_BIT                28
#define IA32E_VTX_VMCS_PROCBASED_CTLS_MONITOR_EXITING_BIT            29
#define IA32E_VTX_VMCS_PROCBASED_CTLS_SECONDARY_CTLS_BIT             31

#define IA32E_VTX_VMCS_PROCBASED_CTLS2_EPT_BIT                       1
#define IA32E_VTX_VMCS_PROCBASED_CTLS2_VPID_BIT                      5
#define IA32E_VTX_VMCS_PROCBASED_CTLS2_WBINVD_EXITING_BIT            6
#define IA32E_VTX_VMCS_PROCBASED_CTLS2_URG_BIT                       7
#define IA32E_VTX_VMCS_PROCBASED_CTLS2_ENCLS_EXITING_BIT             15

#define IA32E_VTX_VMCS_EXIT_CTLS_HOST_ADDRESS_SPACE_SIZE_BIT         9
#define IA32E_VTX_VMCS_EXIT_CTLS_ACKNOWLEDGE_INTERRUPT_ON_EXIT_BIT   15
#define IA32E_VTX_VMCS_EXIT_CTLS_SAVE_PAT_BIT                        18
#define IA32E_VTX_VMCS_EXIT_CTLS_LOAD_PAT_BIT                        19
#define IA32E_VTX_VMCS_EXIT_CTLS_SAVE_EFER_BIT                       20
#define IA32E_VTX_VMCS_EXIT_CTLS_LOAD_EFER_BIT                       21
#define IA32E_VTX_VMCS_EXIT_CTLS_SAVE_VMX_PREEMPTION_TIMER_BIT       22

#define IA32E_VTX_VMCS_ENTRY_CTLS_LOAD_PAT_BIT                       14
#define IA32E_VTX_VMCS_ENTRY_CTLS_LOAD_EFER_BIT                      15

#define IA32E_VTX_VMCS_MSR_READ_LOW    0
#define IA32E_VTX_VMCS_MSR_READ_HIGH   1024
#define IA32E_VTX_VMCS_MSR_WRITE_LOW   2048
#define IA32E_VTX_VMCS_MSR_WRITE_HIGH  3072

#define IA32E_VTX_EPT_UC 0
#define IA32E_VTX_EPT_WC 1
#define IA32E_VTX_EPT_WT 4
#define IA32E_VTX_EPT_WP 5
#define IA32E_VTX_EPT_WB 6

#define IA32E_VTX_VMCS_VECTORED_EVENTS_INFO_VECTOR_MASK             0xffU
#define IA32E_VTX_VMCS_VECTORED_EVENTS_INFO_EVENT_TYPE_SHIFT        8
#define IA32E_VTX_VMCS_VECTORED_EVENTS_INFO_EVENT_TYPE_MASK         (7U << 8)
#define IA32E_VTX_VMCS_VECTORED_EVENTS_INFO_ERRCODE_MASK            (1U << 11)
#define IA32E_VTX_VMCS_VECTORED_EVENTS_INFO_NMI_UNBLOCKING_MASK     (1U << 12)
#define IA32E_VTX_VMCS_VECTORED_EVENTS_INFO_VALID_MASK              (1U << 31)

#define IA32E_VTX_VMCS_EXIT_REASON_MASK                 0xffffU
#define IA32E_VTX_VMCS_EXIT_REASON_ENCLAVE_MASK         (1U << 27)
#define IA32E_VTX_VMCS_EXIT_REASON_VMENTRY_FAILURE_MASK (1U << 31)

#define IA32E_VTX_VMCS_GUEST_INTERRUPTIBILITY_STATE_STI_MASK        (1 << 0)
#define IA32E_VTX_VMCS_GUEST_INTERRUPTIBILITY_STATE_MOV_SS_MASK     (1 << 1)
#define IA32E_VTX_VMCS_GUEST_INTERRUPTIBILITY_STATE_SMI_MASK        (1 << 2)
#define IA32E_VTX_VMCS_GUEST_INTERRUPTIBILITY_STATE_NMI_MASK        (1 << 3)

#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_CR_MASK                       0xf
#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_ACCESS_TYPE_SHIFT             4
#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_ACCESS_TYPE_MASK              (3 << 4)
#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_LMSW_OPERAND_TYPE_MASK        (1 << 6)
#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_GPR_SHIFT                     8
#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_GPR_MASK                      (3 << 8)
#define IA32E_VTX_VMCS_CR_ACCESS_QUAL_LMSW_SOURCE_MASK              (0xffff << 16)

#define IA32E_VTX_VMCS_DB_QUAL_BR_MASK      0xf
#define IA32E_VTX_VMCS_DB_QUAL_BLD_MASK     (1 << 11)
#define IA32E_VTX_VMCS_DB_QUAL_BD_MASK      (1 << 13)
#define IA32E_VTX_VMCS_DB_QUAL_BS_MASK      (1 << 14)
#define IA32E_VTX_VMCS_DB_QUAL_RTM_MASK     (1 << 16)

typedef enum ia32eVtxVmcsCrAccessType
{
    IA32E_VTX_VMCS_MOV_TO_CR =      0,
    IA32E_VTX_VMCS_MOV_FROM_CR =    1,
    IA32E_VTX_VMCS_CLTS =           2,
    IA32E_VTX_VMCS_LMSW =           3
} ia32eVtxVmcsCrAccessType_t;

#define IA32E_VTX_VMCS_LMSW_OPERAND_REG 0
#define IA32E_VTX_VMCS_LMSW_OPERAND_MEM 1

typedef enum ia32eVtxVmcsGpr
{
    IA32E_VTX_VMCS_GPR_RAX =    0,
    IA32E_VTX_VMCS_GPR_RCX =    1,
    IA32E_VTX_VMCS_GPR_RDX =    2,
    IA32E_VTX_VMCS_GPR_RBX =    3,
    IA32E_VTX_VMCS_GPR_RSP =    4,
    IA32E_VTX_VMCS_GPR_RBP =    5,
    IA32E_VTX_VMCS_GPR_RSI =    6,
    IA32E_VTX_VMCS_GPR_RDI =    7,
    IA32E_VTX_VMCS_GPR_R8 =     8,
    IA32E_VTX_VMCS_GPR_R9 =     9,
    IA32E_VTX_VMCS_GPR_R10 =    10,
    IA32E_VTX_VMCS_GPR_R11 =    11,
    IA32E_VTX_VMCS_GPR_R12 =    12,
    IA32E_VTX_VMCS_GPR_R13 =    13,
    IA32E_VTX_VMCS_GPR_R14 =    14,
    IA32E_VTX_VMCS_GPR_R15 =    15
} ia32eVtxVmcsGpr_t;

typedef struct ATTR_PACKED ia32eVtxVmxonRegion
{   
    uint32_t header;
    uint32_t abortId;
    char data[4088];
}  ia32eVtxVmxonRegion_t;
SIZE_ASSERT(ia32eVtxVmxonRegion_t, 4096);

typedef struct ATTR_PACKED ia32eVtxVmcsRegion
{   
    uint32_t header;
    uint32_t abortId;
    char data[4088];
}  ia32eVtxVmcsRegion_t;
SIZE_ASSERT(ia32eVtxVmcsRegion_t, 4096);

typedef struct ATTR_PACKED ia32eVtxMsrEntry
{
    uint32_t msrIndex;
    uint32_t reserved0;
    uint64_t msrData;
} ia32eVtxMsrEntry_t;
SIZE_ASSERT(ia32eVtxMsrEntry_t, 16);

typedef enum ia32eVtxVmcsGuestActivityState
{
    IA32E_VTX_VMCS_GUEST_ACTIVE =           0,
    IA32E_VTX_VMCS_GUEST_HLT =              1,
    IA32E_VTX_VMCS_GUEST_SHUTDOWN =         2,
    IA32E_VTX_VMCS_GUEST_WAIT_FOR_SIPI =    3,
} ia32eVtxVmcsGuestActivityState_t;

#endif